// src/components/Footer.vue
<template>
  <footer class="footer">
    <p>CONTACT</p>
    <div class="follow-links">
      <ul class="menu">
        <li>
          <a href="https://twitter.com/ise0615/" target="_blank">
            <font-awesome-icon :icon="['fab', 'twitter']" />
            <span>Twitter</span>
          </a>
        </li>
        <li>
          <a href="https://www.facebook.com/ise0615/" target="_blank">
            <font-awesome-icon :icon="['fab', 'facebook']" />
            <span>Facebook</span>
          </a>
        </li>
        <li>
          <a href="https://www.instagram.com/isystk/" target="_blank">
            <font-awesome-icon :icon="['fab', 'instagram']" />
            <span>Instagram</span>
          </a>
        </li>
        <li>
          <a href="https://github.com/isystk/" target="_blank">
            <font-awesome-icon :icon="['fab', 'github']" />
            <span>GitHub</span>
          </a>
        </li>
      </ul>
    </div>
    <div class="copylight">
      © 2020 isystk's blog
    </div>
  </footer>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";

@Component
export default class Footer extends Vue {}
</script>

// src/components/organisms/Footer/index.tsx
import React from 'react';
import styles from './styles.module.scss';
import Logo from '@/components/atoms/Logo';
import SocialButtons, { SocialLink } from '@/components/molecules/SocialButtons';

const Footer = () => {
  const links: SocialLink[] = [
    {
      href: 'https://www.facebook.com/ise0615/',
      label: 'Facebook',
      iconType: 'facebook',
    },
    {
      href: 'https://x.com/ise0615/',
      label: 'X(Twitter)',
      iconType: 'twitter',
    },
    {
      href: 'https://www.instagram.com/isystk/',
      label: 'Instagram',
      iconType: 'instagram',
    },
    {
      href: 'https://github.com/isystk/',
      label: 'GitHub',
      iconType: 'github',
    },
  ];

  return (
    <footer className={styles.footer}>
      <div className={styles.footerInner}>
        <SocialButtons links={links} />
        <div className={styles.footerCopy}>
          <small>© 2026</small>
          <Logo hasLink={false} text="isystk's Portfolio" className={styles.footerLogo} />
        </div>
      </div>
    </footer>
  );
};

export default Footer;
